/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 creature.glb 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model({ meshes, onHover, ...props }) {
  const { nodes, materials } = useGLTF('/creature.glb')
  const { meshRef1, meshRef2, meshRef3 } = meshes

  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.body.geometry} material={nodes.body.material} />
      <mesh ref={meshRef1} geometry={nodes.righteye.geometry} /* onPointerOver={(e) => onHover(meshRef1)} */ material={nodes.righteye.material} position={[-0.013, -0.021, 0.004]} rotation={[-0.023, 0.446, 0.142]} />
      <mesh ref={meshRef2} geometry={nodes.lefteye.geometry} /* onPointerOver={(e) => onHover(meshRef2)} */ material={nodes.lefteye.material} position={[-0.019, -0.053, 0.031]} rotation={[-0.025, 0.458, 0.142]} />
      <mesh geometry={nodes['guy-upperbody'].geometry} material={nodes['guy-upperbody'].material} position={[-0.065, -0.318, 0.3]} rotation={[0.023, 0, 0]} scale={[0.474, 0.46, 0.527]}>
        <group position={[-0.006, 0, 0]} rotation={[0, -0.738, 0]} scale={[1.003, 1, 0.997]}>
          <mesh geometry={nodes['guy-leftlens'].geometry} material={nodes['guy-leftlens'].material} rotation={[0, 0.833, 0]} />
        </group>
        <group position={[0.005, 0, -0.011]} rotation={[0, 0.731, Math.PI]} scale={[1.003, 1, 0.997]}>
          <mesh geometry={nodes['guy-rightlens'].geometry} material={nodes['guy-rightlens'].material} rotation={[0, 0.84, -Math.PI]} />
        </group>
        <group position={[-0.007, 0, 0.002]} rotation={[0, -0.754, 0]} scale={[1.002, 1, 0.998]}>
          <mesh geometry={nodes['guy-glassesbridge'].geometry} material={nodes['guy-glassesbridge'].material} rotation={[0, 0.817, 0]} />
        </group>
        <group position={[-0.001, 0.004, 0.121]} rotation={[2.308, 0.205, 1.382]} scale={[1.003, 1, 0.997]}>
          <mesh geometry={nodes['guy-glassesleft'].geometry} material={nodes['guy-glassesleft'].material} rotation={[3.061, 0.726, 1.348]} />
        </group>
        <group position={[0.001, 0, -0.001]} rotation={[0, 0.752, -Math.PI]} scale={[1.002, 1, 0.998]}>
          <mesh geometry={nodes['guy-glassesright'].geometry} material={nodes['guy-glassesright'].material} rotation={[0, 0.819, Math.PI]} />
        </group>
        <mesh geometry={nodes['guy-phone'].geometry} material={nodes['guy-phone'].material} position={[0, -0.007, 0.081]} rotation={[-0.182, 0, 0]} />
        <mesh geometry={nodes['guy-rightsole'].geometry} material={nodes['guy-rightsole'].material} position={[0, -0.012, 0.017]} rotation={[0.038, 0, 0]} />
        <mesh geometry={nodes['guy-leftsole'].geometry} material={nodes['guy-leftsole'].material} position={[0, -0.012, 0.017]} rotation={[0.038, 0, 0]} />
        <mesh geometry={nodes['guy-leftsock'].geometry} material={nodes['guy-leftsock'].material} position={[0, -0.012, 0.017]} rotation={[0.038, 0, 0]} />
        <mesh geometry={nodes['guy-rightsock'].geometry} material={nodes['guy-rightsock'].material} position={[0, -0.012, 0.017]} rotation={[0.038, 0, 0]} />
        <mesh geometry={nodes['guy-rightshoe'].geometry} material={nodes['guy-rightshoe'].material} position={[0, -0.012, 0.017]} rotation={[0.038, 0, 0]} />
        <mesh geometry={nodes['guy-leftshoe'].geometry} material={nodes['guy-leftshoe'].material} position={[0, -0.012, 0.017]} rotation={[0.038, 0, 0]} />
        <mesh geometry={nodes['guy-jacket'].geometry} material={nodes['guy-jacket'].material} />
        <mesh ref={meshRef3} geometry={nodes['guy-trousers'].geometry} material={nodes['guy-trousers'].material} />
        <mesh geometry={nodes['guy-righthand'].geometry} material={nodes['guy-righthand'].material} position={[0, -0.007, 0.081]} rotation={[-0.182, 0, 0]} />
        <mesh geometry={nodes['guy-lefthand'].geometry} material={nodes['guy-lefthand'].material} position={[0, -0.007, 0.081]} rotation={[-0.182, 0, 0]} />
      </mesh>
      <pointLight intensity={2.845} decay={2} color="#a63ad9" position={[-0.045, -0.321, 0.418]} rotation={[-0.796, 0.579, 0.249]} />
      <spotLight intensity={6.251} angle={0.469} penumbra={1} decay={2} color="#a07e92" position={[-0.107, 1.466, -0.062]} rotation={[-1.63, 0.004, 0.005]} />
    </group>
  )
}

useGLTF.preload('/creature.glb')
